name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package -DskipTests=false

    - name: Run Unit Tests
      run: mvn test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker image
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        IMAGE_NAME:  cashcard-app
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest