name: Production SQL Review Policy

on:
  pull_request:
    branches:
      - master
    paths:
      - "src/main/resources/db/migration/**.sql"
      - "resources/db/migration/**.sql"

jobs:
  check-release-on-prod:
    permissions:
      pull-requests: write # write permission required to allow the action writes the check results to the comment.
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # set GITHUB_TOKEN because the 'Check release' step needs it to comment the pull request with check results.
      BYTEBASE_URL: https://positive-robin-similarly.ngrok-free.app
      BYTEBASE_SERVICE_ACCOUNT: cashcard-app@service.bytebase.com
      BYTEBASE_PROJECT: "projects/cashcard-project"
      BYTEBASE_TARGETS: "instances/mysql-prodasia-instance/databases/operator_cashcard"
      FILE_PATTERN: "src/main/resources/db/migration/**/*.sql"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/login-action@v1
        with:
          bytebase-url: ${{ env.BYTEBASE_URL }}
          service-key: ${{ env.BYTEBASE_SERVICE_ACCOUNT }}
          service-secret: ${{secrets.BYTEBASE_SERVICE_ACCOUNT_SECRET}} # Please use secrets for sensitive data in production.
      - name: Check release
        uses: bytebase/create-release-action@v1
        with:
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          file-pattern: ${{ env.FILE_PATTERN }}
          # fail the action if release checks report any error.
          check-release: "FAIL_ON_ERROR"
          project: ${{ env.BYTEBASE_PROJECT }}
          targets: ${{ env.BYTEBASE_TARGETS }}
          validate-only: true
